title: Tyler Desharnais Resume
author: Ty Desharnais
email: tydesharnais1998@gmail.com.com
description: > # this means to ignore newlines until "baseurl:"
  Tyler Desharnais GitHub Resume. Building a better future through technological advancements,
  Software Engineering, Robotics, and Artifical Intelligence
  
  


# social links
twitter_username: tydesharnais # DO NOT include the @ character, or else the build will fail!
github_username:  tydesharnais # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
